---
title: "Queer Coded: Supervised ML to Predict LGBTQ+ Acceptance in American Neighborhoods"
subtitle: "Final Project Progress Memo 2-- STAT 301-3 Data Science 3 with R"
author: "Vlad Nevirkovets, Sean Pascoe, Dylan Yan"
date: today
format: 
  html:
    embed-resources: true
    toc: true
    link-external-newwindow: true
    df-print: paged
    footnotes-hover: true
title-block-banner: images/pride-geotag.png
title-block-banner-color: black
execute:
  echo: false
  warning: false
from: markdown+emoji
editor_options: 
  chunk_output_type: console
---
::: {.callout-tip icon="false"}
## Github Repo Link

<https://github.com/STAT301-3-2023SP/final-project-central-limit-heros>
:::


### Introduction

Neighborhoods with a high queer population, or [*Gayborhoods*](https://en.wikipedia.org/wiki/Gay_village), have been urban areas in which LGBTQ+ people have found community and built culture worldwide. However, these geographic areas serve as much more than the sexuality of their constituents, and have been cited as yielding robust creative economies, as well as a welcoming environment for those of many identities. Knowing this, the identity of a certain locale as a Gayborhood becomes a crucial sociological metric, with neighborhoods with a more prevalent queer identity driving social liberalism in the face of prejudice. Our analysis thus focuses on building a **location-based regression model** that uses a variety of parameters including housing, land use, and non-queer demographic data **to predict Gayborhood degree**, and, in so doing, determine whether an area is suitable for queer folks with the goal of advancing understanding of liberal areas.

### Outcome Variable

In order to rank Gayborhood status, we are using a published dataset [from data world](https://data.world/the-pudding/gayborhoods)[^1] that was analyzed to display distribution of queer communities in Jan Diehm's 2018 article [*Men are from Chelsea, Women are from Park Slope*](https://pudding.cool/2018/06/gayborhoods/). Specifically, the metrics in this dataset are combined to form a Gayborhood index, which we will use as the supervising variable for our machine learning project. This index is a holistic assessment of queerness, derived primarily from the following measures:

[^1]: Jan Diehm. (2018). *Gayborhoods* [Data set]. *The Pudding*, data.world. https://data.world/the-pudding/gayborhoods. Accessed 10 April 2023.

- Same-sex joint tax filers
- Unmarried partner same sex households
- Number of Gay Bars
- Whether or not a pride parade routes through the region

In this case, we will be training a regression model to predict Gayborhood index. The initial variable exists on a 0 to 100 scale with a mean of 2.39, median of 1.27, and a max of 67.1. Because of this heavy right skew, we are choosing to model the log 10 transformation of the data, which is significantly more normal, and will thus fit better with our chosen models:


## Data collection

we did a lot of work here lowkey . we should talk about it


## EDA 

did we just not have missingness?? i think there was some or else what are we imputing... lol.

DEFINITELY talk about the yeo johnson transform or whatever we did there. that was tea .


# overview of modeling process

```{r}
#| label: mermaiddd

DiagrammeR::mermaid("
  graph LR
    A[Tree Data]-->D(Feature Engineering)
    B[Census Data]-->D
    C[Bike Data]-->D
    D-->E(Initial Modeling)
    E-->F[Model Selection]
    E-->F
    E-->F
    E-->F
    E-->F
    E-->F
    F-->G[Ensemble Fitting]
    F-->G
    F-->G
    G-->H(Model Assessment)
")
```


## Initial modeling

we fit these model types:

- Penalized Elastic Net Regression
    - with and without [partial least squares](https://en.wikipedia.org/wiki/Partial_least_squares_regression)

- Random Forest + Boosted Tree (?)

- K-Nearest Neighbors

- Neural Networks 
  - Basic neural networks using `nnet` in R
  - Using `keras` and [Tensorflow](https://www.tensorflow.org/) from python through R
  
- Multivariate Adaptive Regression Splines

- Cubist ensemble regression


***WHATS THE SITCH WITH OTHER RECIPES?? DO WE WANT TO TRY THEM NOW??***


## Model selection 

we picked the three best ones

## ensemble modeling

yay for stacks. we might actually want to try [baguette](https://baguette.tidymodels.org/index.html) instead, i feel like it slays, but i didnt do the reading so i owuldnt know.


## final results

happy pride <3 such a well timed project tbh

